Adapt get_object_attributes to `git cat-file` output after format change
When dealing with ambiguous SHA1, the code expected output like the
following:

    $ echo 577ecc | git cat-file --batch-check
    error: short SHA1 577ecc is ambiguous.
    577ecc missing

Since version 2.11.0.rc0, the output became ("error:" and "hint:" lines
are produced on STDERR), i.e. with an extra line on STDOUT:

    $ echo 577ecc | git cat-file --batch-check
    error: short SHA1 577ecc is ambiguous
    hint: The candidates are:
    hint:   577ecc2 blob
    hint:   577ecca blob
    dangling 6
    577ecc